### ISSUE TITLE
Authorization: config or default to Bearer token approach

### ISSUE THREAD

**Issue by simranbentel** [cloud-annotations/docusaurus-plugin-openapi#67] opened 2021-11-29 23:52 UTC
Is there any way for the Authorization UI to default to the Bearer token input? Users of my site will need to figure out switching the user/pass inputs to Bearer token. I tried use CSS to alter the presentation but the React logic is not allowing that approach.

**Comment by bourdakos1** [comment] 2021-11-30 00:20
I think this might be a bug. The intended behavior is that you would only have to toggle between auth modes that are specified in the OpenAPI definition (in the order that they are listed), but I think the component incorrectly always shows both basic and bearer auth modes when any auth modes are listed.

I am unable to make any contributions at the moment, but I believe @avaidyam added the basic auth support, so he might be able to help resolve this.

I am also happy to get a PR merged if you want to attempt to fix this. The relevant code can be found here:
https://github.com/cloud-annotations/docusaurus-plugin-openapi/blob/main/packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/Authorization/index.js

**Comment by avaidyam** [comment] 2021-11-30 14:02
@simranbentel Right, as @bourdakos1 says, it's supposed to work off of the different auth types present in the OpenAPI specification. I recall hardcoding support for basic auth in addition to the previously present Bearer auth. This may take some extra work to implement properly, I think.

**Comment by simranbentel** [comment] 2021-12-02 00:30
> @simranbentel Right, as @bourdakos1 says, it's supposed to work off of the different auth types present in the OpenAPI specification. I recall hardcoding support for basic auth in addition to the previously present Bearer auth. This may take some extra work to implement properly, I think.

Thanks @avaidyam. Looking at the Authorization component I see a clear path to getting the Bearer auth to show by default and hiding the switch button. I will make a fork with those changes for the time being. Will check back to see when you get this fully implemented based on the security scheme. Cheers!

**Comment by bourdakos1** [comment] 2021-12-05 01:00
I should be able to work on this now

**Comment by bourdakos1** [comment] 2021-12-06 04:38
@simranbentel This should be available in the next release

**Closed** 2021-12-06 04:38 UTC

**Comment by simranbentel** [comment] 2021-12-08 18:16
@bourdakos1 I have installed v0.2.2 and integrated via preset. The Authorization panel contains only a "Save" button for me. No input is being rendered.

In my swagger json `components` contains:
`"securitySchemes": {
      "Bearer": {
        "type": "http",
        "description": "Put your **API key** (JWT or Reference token) on textbox below (without 'Bearer ' prefix)",
        "scheme": "Bearer",
        "bearerFormat": "JWT or Reference token"
      }
    }`

and each endpoint method contains:
`"security": [
          {
            "Bearer": [
              "sample.endpoint.id"
            ]
          }
        ]`

Expected: Bearer input should display as in v0.1 of the package. 
Actual: No input is displayed.

Is this still being worked on?

**Comment by bourdakos1** [comment] 2021-12-08 18:50
@simranbentel it expects `scheme` to be `bearer` (all lowercase). I'm not super well versed in how these security schemes are intended to work, should `scheme` not be case sensitive?

**Comment by simranbentel** [comment] 2021-12-08 21:02
> @simranbentel it expects `scheme` to be `bearer` (all lowercase). I'm not super well versed in how these security schemes are intended to work, should `scheme` not be case sensitive?

Hmm, not sure regarding case sensitivity. I can try and see if the value can be changed from the backend I am getting json from. You could also add `.toLowerCase()` if you are willing to make that change on your side.

**Comment by bourdakos1** [comment] 2021-12-08 22:05
Yea, I can do that :) Do you mind opening a separate issue for this?

**Comment by bourdakos1** [comment] 2021-12-08 22:10
Looks like scheme is intended to be case insensitive https://github.com/OAI/OpenAPI-Specification/issues/1876

**Comment by bourdakos1** [comment] 2021-12-11 20:00
@simranbentel `Bearer` should now work in v0.2.3

**Comment by simranbentel** [comment] 2021-12-13 16:49
@bourdakos1 Confirmed, it is working now. Thank you!
