### ISSUE TITLE
Error in openapiPath?

### ISSUE THREAD

**Issue by MiguelPreto** [cloud-annotations/docusaurus-plugin-openapi#21] opened 2021-03-24 13:19 UTC
Hey there, I don't know if this is a issue or if I did something wrong, but, I followed the steps and I get an error:
<img width="686" alt="Screenshot 2021-03-24 at 13 18 35" src="https://user-images.githubusercontent.com/74260097/112316922-7545d200-8ca3-11eb-87dc-a9b3c2d8825b.png">

I started to play some things and I added a json stringify in the openapiPath:
<img width="553" alt="Screenshot 2021-03-24 at 13 13 04" src="https://user-images.githubusercontent.com/74260097/112316091-affb3a80-8ca2-11eb-8b80-ffd10fad398a.png">

After that the error disappeared, but I couldn't see the API page:
![Screenshot 2021-03-24 at 13 14 48](https://user-images.githubusercontent.com/74260097/112316436-049eb580-8ca3-11eb-9408-f41488baadea.png)

Did I do something wrong or is this a bug?
Thanks in advance!

**Comment by bourdakos1** [comment] 2021-03-24 14:27
Do you mind sharing your openapi.json file?

**Comment by MiguelPreto** [comment] 2021-03-24 14:34
openapi.json file:

`{"openapi":"","info":{"title":"","version":""},"paths":{"/health":{"get":{"responses":{"200":{"description":"OK"}}}},"/api/account/links/{partnerId}":{"post":{"description":"This method receives an authorization token. That token will be used to get the user's tokens."}},"/account/pairs/{pairId}/linking-caps":{"get":{}},"/api/aoi/subscriptions":{"post":{"description":"This method will create a new AOI subscription"}},"/api/aoi/subscriptions/pair/{pairId}":{"get":{"description":"This method will return the AOI subscription based on the user session and the linked account"},"delete":{"description":"This method will delete the current aoi subscription for a given pair"}},"/api/exchange/orders/{transactionId}":{"get":{}},"/api/feedback/contact-us":{"post":{}},"/maintenance/partners/{partnerId}/accounts/{accountId}/history":{"delete":{}},"/partners/accounts/{accountId}/links/{partnerId}/exists":{"get":{"description":"Proxy to PAUL's check if link exists"}}},"components":{}}`

<img width="1218" alt="Screenshot 2021-03-24 at 14 34 09" src="https://user-images.githubusercontent.com/74260097/112328203-05891480-8cae-11eb-9d12-433dc817f45f.png">

**Comment by MiguelPreto** [comment] 2021-03-25 14:33
Hey man, already know what is wrong, apparently the @summary tag is mandatory and I didn't had it.
So the fix is to add the tag @summary to the openapi.json, so it would be something like:

`{"openapi":"","info":{"title":"","version":""},"paths":{"/":{"get":{"responses":{"200":{"description":"OK"}},"summary":"/","description":"/"}},"/health":{"get":{"responses":{"200":{"description":"OK"}},"summary":"test"}},"/accounts/{internalId}":{"get":{}},"/accounts":{"post":{"description":"This method receives an object to be inserted"}},"/accounts/:internalId/pairs/:pairId/caps":{"get":{}},"/maintenance/partners/{partnerId}/accounts/{accountId}/history":{"delete":{}},"/partners/{ownerId}/accounts/{accountId}/links":{"post":{"description":"This method receives an authorization token. That token will be used to get the user's tokens."}},"/partners/:ownerId/accounts":{"post":{"description":"This method receives an authorization token. That token will be used to get the user's tokens from BA"}}},"components":{}}`

**Comment by bourdakos1** [comment] 2021-03-25 14:45
Oh I think this is a bug, I will try to fix this by the weekend

**Comment by MiguelPreto** [comment] 2021-03-25 14:47
Awesome!

**Comment by bourdakos1** [comment] 2021-03-26 15:45
I think the issue is actually because of a missing description, I think I've fixed the issue. Releasing now

**Comment by bourdakos1** [comment] 2021-03-26 17:19
@MiguelPreto your original `openapi.json` is now working for me so I'm going to close this. Feel free to reopen if you're still having issues with v0.0.15

**Closed by bourdakos1** 2021-03-26 17:19 UTC
